language: elixir
sudo: false
elixir:
  - 1.7
  - 1.8
otp_release:
  - 20.3
  - 18.2.1
notifications:
  recipients:
    - travis@coryodaniel.com
jobs:
  include:
    - stage: test
      script: make test/all
    - stage: coverage
      script: mix coveralls.travis
